import 'package:flutter/material.dart';
import 'package:taske_commerceresponsive/datamodel.dart';
import 'package:taske_commerceresponsive/widget/categorytext.dart';
import 'package:taske_commerceresponsive/widget/header.dart';
import 'package:taske_commerceresponsive/widget/myappbar.dart';
import 'package:taske_commerceresponsive/widget/tabbar.dart';

class Homepage extends StatefulWidget {
  const Homepage({super.key});

  static List<ProductModel> items = [
    ProductModel(
        path: "assets/images/Mens premium Shirt's.jpg",
        name: "mens premium   shirt",
        price: 1800,
        rating: "4.5",
        //z image: ["assets/images/Mens premium Shirt's1.jpg","assets/images/Mens premium Shirt's.jpg","assets/images/Mens premium Shirt's1.jpg"],
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
    ProductModel(
        path: "assets/images/Mens premium Shirt's1.jpg",
        name: "mens premium   shirt",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
    ProductModel(
        path: "assets/images/Mens premium Shirt's2.jpg",
        name: "mens premium   shirt",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
    ProductModel(
        path: "assets/images/Mens premium Shirt's3.jpg",
        name: "mens premium   shirt",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
    ProductModel(
        path: "assets/images/Womens Sweat Shirt's.jpg",
        name: "womens premium shirt",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "women"),
    ProductModel(
        path: "assets/images/Womens Sweat Shirt's1.jpg",
        name: "womens premium shirt",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "women"),
    ProductModel(
        path: "assets/images/Womens Sweat Shirt's2.jpg",
        name: "womens premium shirt",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "women"),
    ProductModel(
        path: "assets/images/Womens Sweat Shirt's3.jpg",
        name: "womens premium shirt",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "women"),
    ProductModel(
        path: "assets/images/Kids Dress.jpg",
        name: "kids premium cloth",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "kids"),
    ProductModel(
        path: "assets/images/Kids Dress1.jpg",
        name: "kids premium cloth",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "kids"),
    ProductModel(
        path: "assets/images/Kids Dress2.jpg",
        name: "kids premium cloth",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "kids"),
    ProductModel(
        path: "assets/images/Kids Dress3.jpg",
        name: "kids premium cloth",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "kids"),
    ProductModel(
        path: "assets/images/Mens T-Shirt's.jpg",
        name: "Mens T-Shirt ",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
    ProductModel(
        path: "assets/images/Mens T-Shirt's1.jpg",
        name: "Mens T-Shirt ",
        price: 1800,
        rating: "4.5",
        quantity: 50,
        image: [
          "assets/images/black1.jpeg",
          "assets/images/black2.jpeg",
          "assets/images/black3.jpeg"
        ],
        image1: [
          "assets/images/red1.jpg",
          "assets/images/red2.jpg",
          "assets/images/red3.jpg",
        ],
        image2: [
          "assets/images/white1.jpeg",
          "assets/images/white2.jpeg",
          "assets/images/white3.jpeg"
        ],
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
    ProductModel(
        path: "assets/images/Mens T-Shirt's2.jpg",
        name: "Mens T-Shirt ",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
    ProductModel(
        path: "assets/images/Mens T-Shirt's3.jpg",
        name: "Mens T-Shirt ",
        price: 1800,
        rating: "4.5",
        smallavailable: true,
        largeavailable: true,
        mediumavailable: true,
        xlavailable: true,
        color1: Colors.black,
        color2: Colors.white,
        color3: Colors.green,
        category: "men"),
  ];

  @override
  State<Homepage> createState() => _HomepageState();
}

class _HomepageState extends State<Homepage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: const MyAppBar(),
      body: Column(
        children: const [
          Padding(
            padding: EdgeInsets.all(8.0),
            child: Header(),
          ),
          SizedBox(
            height: 10,
          ),
          Category(),
          SizedBox(
            height: 30,
          ),
          Expanded(child: MyTabBar()),
        ],
      ),
    );
  }
}
